/* DO NOT EDIT, file generated by nestjs-i18n */

import { Path } from "nestjs-i18n";
export type I18nTranslations = {
    "alerts": {
        "language_already_exists": string;
    };
    "buttons": {
        "back": string;
        "change_language": string;
        "faq": string;
    };
    "phrases": {
        "home": string;
        "change_language": string;
        "faq": string;
    };
    "languages": {
        "en": string;
        "ru": string;
    };
    "scenes": {
        "home": {};
        "change_language": {};
        "faq": {};
    };
};
export type I18nPath = Path<I18nTranslations>;
